[package]
name = "ease-client-tokio"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros"] }
once_cell = "1.18.0"
