package com.kutedev.easemusicplayer.turintegration

/**
 * JNI bridge to the native tur engine standard operations.
 *
 * Every method is a thin `external fun` over the `Java_org_tur_TurNative_*`
 * entry points that `libease_client_backend.so` exports (generated by
 * `tur_android::standard_jni_exports!()` in `rust-libs/ease-client-backend/
 * src/plugin_runtime/plugin_jni.rs`).
 *
 * The library is loaded once by `EaseMusicPlayerApplication`'s
 * `companion object { init { System.loadLibrary("ease_client_backend") } }`,
 * so this object doesn't need its own `System.loadLibrary` call — the
 * external-fn bindings resolve against the already-loaded library.
 *
 * Handle-based and stateless: the same object safely drives any number
 * of engine instances (one per [TurView]).
 */
object TurNative {
    /** Evaluate [js] as an ES module (`import … from "tur:*"` resolved by the engine). */
    external fun loadModule(handle: Long, js: String)

    /** Fire one engine wake — call each Choreographer / Handler tick. */
    external fun pump(handle: Long): Int

    /** Push a new surface size (logical px + dpr). */
    external fun resize(handle: Long, width: Int, height: Int, dpr: Double)

    /**
     * Push a pointer event. [action] matches `MotionEvent.ACTION_*`:
     * `0=DOWN`, `1=UP`, `2=MOVE`, `3=CANCEL`. Coordinates are logical px
     * relative to the surface; [timeMs] is `SystemClock.uptimeMillis()`.
     */
    external fun pushPointer(handle: Long, action: Int, x: Double, y: Double, timeMs: Long)

    /**
     * Push a key event. [action] is `0=DOWN`, `1=UP`. [key]/[code] are
     * browser-style strings (see [InputMapper] for the Android→browser map).
     */
    external fun pushKey(
        handle: Long,
        key: String,
        code: String,
        action: Int,
        ctrl: Boolean,
        shift: Boolean,
        alt: Boolean,
        meta: Boolean,
    )

    /**
     * Whether the currently-focused element is an editable text field.
     */
    external fun focusedIsEditable(handle: Long): Boolean

    /**
     * Push an IME composition event. [kind]: `0=CompositionStart`,
     * `1=CompositionUpdate { text }`, `2=CompositionEnd { text }`.
     */
    external fun pushIme(handle: Long, kind: Int, text: String)

    /** Drop the engine and free its resources. */
    external fun destroy(handle: Long)
}
