name: ease_music_player
description: A simple music player supporting play from WebDAV, FTP and other your owned devices.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.19

environment:
  sdk: ">=3.0.5 <4.0.0"

flutter:
  assets:
    - assets/icons/
    - assets/
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.34
  ffi: ^2.1.0
  flutter_rust_bridge: 1.82.6
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.0.5
  audio_service: ^0.18.12
  permission_handler: ^11.0.1
  flutter_svg: ^2.0.7
  package_info_plus: ^5.0.1
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^8.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
