# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = ["ease-client-backend", "ease-client-android-ffi-builder"]

[profile.bench]
debug = true
opt-level = 3
