# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "ease-database",
    "misty-serve",
    "ease-client-shared",
    "ease-remote-storage",
    "ease-client-backend",
    "ease-client",
    "ease-client-test",
    "ease-client-android-ffi-builder",
]
