[package]
name = "misty-serve"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.57"
futures = "0.3.30"
anyhow = "1.0.80"
rmp-serde = "1.3.0"
